name: BlockRegenerator
version: 1.0
main: me.joshuaemq.blockregenerator.BlockRegeneratorPlugin
description: RegenerateBlocks!
depend: [Facecore]
softdepend: [WorldGuard, WorldEdit]

commands:
  blockregen:
    aliases: [br]

permissions:
  blockregen.command.reload:
    default: op